import { SupabaseService } from '../supabase/supabase.service';
export declare const DECISION_TYPES: readonly ["APPROVED", "REJECTED", "CONDITIONAL_SANCTION", "COUNTER_OFFER", "PARTIAL_SANCTION"];
export type DecisionType = typeof DECISION_TYPES[number];
export declare const REJECTION_CATEGORIES: readonly ["CIBIL", "INCOME", "DOCS", "FRAUD", "POLICY", "TECHNICAL", "OTHER"];
export type RejectionCategory = typeof REJECTION_CATEGORIES[number];
export declare const ROI_TYPES: readonly ["FIXED", "FLOATING", "SUBSIDY"];
export type RoiType = typeof ROI_TYPES[number];
export declare const FEE_MODES: readonly ["ONLINE", "CHEQUE", "DD", "WAIVER"];
export type FeeMode = typeof FEE_MODES[number];
export declare const PREDEFINED_TAGS: readonly ["PRIORITY", "URGENT", "QUERY_PENDING", "DOCS_MISSING", "HIGH_VALUE", "SUBSIDY_CASE", "COLLATERAL", "CO_APPLICANT", "RESUBMISSION", "ESCALATED", "SBI_SCHEME", "VIDYA_LAKSHMI", "ABROAD_STUDY", "DOMESTIC_STUDY", "FOLLOW_UP"];
export declare class BankDashboardService {
    private readonly supabase;
    constructor(supabase: SupabaseService);
    private get db();
    getBankProducts(bankId: string): Promise<any[]>;
    addBankProduct(bankId: string, productData: any): Promise<any>;
    updateBankProduct(productId: string, productData: any): Promise<any>;
    getBankBranches(bankId: string): Promise<any[]>;
    addBankBranch(bankId: string, branchData: any): Promise<any>;
    logFileWithLAN(applicationId: string, lanNumber: string, bankUser: any): Promise<any>;
    getFilesByLAN(lanNumber: string): Promise<any>;
    setROI(applicationId: string, roiData: any, bankUser: any): Promise<any>;
    setProcessingFee(applicationId: string, feeData: any, bankUser: any): Promise<any>;
    updateProcessingFeeStatus(applicationId: string, status: string, details: any): Promise<any>;
    raiseQuery(applicationId: string, queryData: any, bankUser: any): Promise<any>;
    respondToQuery(queryId: string, response: any, bankUser: any): Promise<any>;
    resolveQuery(queryId: string, bankUser: any): Promise<any>;
    confirmDisbursement(applicationId: string, disbursementData: any, bankUser: any): Promise<any>;
    getDisbursements(applicationId: string): Promise<any[]>;
    rateFileQuality(applicationId: string, ratingData: any, bankUser: any): Promise<any>;
    getChannelAnalytics(bankId: string): Promise<any>;
    getRejectionAnalytics(bankId: string): Promise<any>;
    getPipelineAnalytics(bankId: string): Promise<any>;
    getAgingReport(bankId: string): Promise<any>;
    getSLAMetrics(bankId: string): Promise<any>;
    private logAudit;
    getAuditLogs(applicationId: string): Promise<any[]>;
    createFileEntry(applicationId: string, bankId: string, fileData: any, bankUser: any): Promise<any>;
    listBankFiles(bankId: string | null, status?: string, lanNumber?: string): Promise<any[]>;
    private normalizeBankName;
    getFileDetails(fileId: string): Promise<any>;
    getFileLog(fileId: string): Promise<any>;
    addDocumentToFile(fileId: string, docData: any, bankUser: any): Promise<any>;
    getFileDocuments(fileId: string): Promise<any[]>;
    getDocumentDetails(fileId: string, documentId: string): Promise<any>;
    downloadFileAsArchive(fileId: string): Promise<any>;
    getFileTimeline(applicationId: string): Promise<any[]>;
    getFileEvents(applicationId: string, type?: string): Promise<any[]>;
    validateLANFormat(lanNumber: string): Promise<any>;
    checkLANExists(lanNumber: string): Promise<any>;
    getLANDetails(lanNumber: string): Promise<any>;
    sanctionApplication(applicationId: string, sanctionData: any, bankUser: any): Promise<any>;
    updateSanction(applicationId: string, sanctionData: any, bankUser: any): Promise<any>;
    recordBankDecision(applicationId: string, decisionData: any, bankUser: any): Promise<any>;
    transitionApplicationStatus(applicationId: string, targetStatus: string, bankUser: any, reason?: string): Promise<any>;
    getAllowedTransitionsForApp(applicationId: string, bankUser: any): Promise<any>;
    getBankQueries(bankId: string, applicationId?: string): Promise<any[]>;
    getQueryDetails(queryId: string): Promise<any>;
    getQueryResponses(queryId: string): Promise<any[]>;
    recordConsent(applicationId: string, consentData: any, bankUser: any): Promise<any>;
    getConsentStatus(applicationId: string): Promise<any>;
    updateReferralFee(applicationId: string, feeData: any, bankUser: any): Promise<any>;
    addNote(fileId: string, noteData: any, bankUser: any): Promise<any>;
    getNotes(fileId: string, bankUser: any): Promise<any[]>;
    updateNote(noteId: string, content: string, bankUser: any): Promise<any>;
    deleteNote(noteId: string, bankUser: any): Promise<void>;
    getTagLibrary(): string[];
    addTag(fileId: string, tag: string, bankUser: any): Promise<any>;
    removeTag(fileId: string, tag: string, bankUser: any): Promise<any>;
    getFilesByTag(tag: string, bankId: string | null): Promise<any[]>;
    private resolveApplicationId;
}
