import { SupabaseService } from '../supabase/supabase.service';
import { SlackService } from './slack.service';
import { SalesforceService } from './salesforce.service';
import { EventEmitter2 } from '@nestjs/event-emitter';
export declare class BankService {
    private readonly supabase;
    private readonly slack;
    private readonly salesforce;
    private readonly eventEmitter;
    constructor(supabase: SupabaseService, slack: SlackService, salesforce: SalesforceService, eventEmitter: EventEmitter2);
    private get db();
    private matchBankFilter;
    getIncomingFiles(bankName: string, filters: any): Promise<any[]>;
    logFile(applicationId: string, lanNumber: string, bankUser: any): Promise<any>;
    getDocuments(applicationId: string): Promise<any[]>;
    generateDocumentsZip(applicationId: string): Promise<any>;
    registerDecision(applicationId: string, decisionType: string, details: any, bankUser: any): Promise<any>;
    raiseQuery(applicationId: string, content: string, bankUser: any): Promise<any>;
    confirmDisbursement(applicationId: string, disbursementAmount: number, trancheNumber: number, transferMode: string, utrNumber: string, bankUser: any): Promise<any>;
    submitFileQualityScore(applicationId: string, rating: number, feedback: string): Promise<any>;
    getSlaTrackingMetrics(bankName: string): Promise<any>;
    getFileDetail(applicationId: string): Promise<any>;
    lookupByLan(lan: string): Promise<any>;
    getMyFiles(bankName: string, filters: any): Promise<any[]>;
    amendDecision(applicationId: string, decisionId: string, details: any, user: any): Promise<any>;
    uploadSanctionLetter(applicationId: string, fileUrl: string, user: any): Promise<any>;
    setRoi(applicationId: string, roiData: any, user: any): Promise<any>;
    setProcessingFee(applicationId: string, feeData: any): Promise<any>;
    updateProcessingFee(applicationId: string, updateData: any): Promise<any>;
    getQueryThread(queryId: string): Promise<any>;
    resolveQuery(queryId: string): Promise<any>;
    getAnalyticsMetrics(bankName: string): Promise<any>;
    getProducts(bankName: string): Promise<any[]>;
    createProduct(productData: any): Promise<any>;
    updateProduct(productId: string, productData: any): Promise<any>;
    getBranches(bankName: string): Promise<any[]>;
    createBranch(branchData: any): Promise<any>;
    getOfficers(bankName: string): Promise<any[]>;
    exportApplicationsCsv(bankName: string): Promise<any>;
    exportMisReports(bankName: string): Promise<any>;
}
