export declare function normalizeStateName(stateStr?: string): string;
export type AcademicLevel = 'grade10' | 'grade12' | 'undergrad' | 'postgrad';
export declare function inferStateFromText(...parts: (string | undefined)[]): string | undefined;
export declare function inferCityFromInstitution(institution?: string): string | undefined;
export declare function parseExamYear(examPeriod?: string): string | undefined;
export declare function examYearToEndDate(examPeriod?: string): string | undefined;
export declare function inferStartDate(endDate: string, yearsBack?: number): string | undefined;
export declare function normalizeGradingSystem(grading?: string, score?: string | number): 'CGPA' | 'Percentage' | '';
export declare function normalizeAcademicScore(score?: string | number, grading?: string): string;
export declare function percentageFromTotalMarks(secured?: string | number, maximum?: string | number): string | undefined;
export declare function formatAcademicDate(dateStr?: string): string | undefined;
export declare function canonicalizeAcademicFields(raw: Record<string, any>, level: AcademicLevel): Record<string, any>;
